### ISSUE TITLE
Support more recent version of decorator

### ISSUE THREAD

**Issue by DManowitz** [fabian-sp/GGLasso#39]
This package has a dependency on decorator v4.4.2.  However, newer versions are available, so I would like to request support for these newer versions.

**Comment by fabian-sp** [comment]
Hi, we fixed the decorator version as it caused an error together with networkx. But this only affects generating synthetic networks, not solving problems. So i think it is safe to manually update decorator.

However I will also test if the causing issue has been resolved in the mean time.
