### ISSUE TITLE
NumPy Versioning Issue 

### ISSUE THREAD

**Issue by Bpoole908** [fabian-sp/GGLasso#42]
It looks like `np.float` is/has been deprecated in NumPy. Currently, GGLasso requires any version of NumPy >= 1.17.3. However, this breaks for versions of NumPy > 1.22.0 where `np.float` has been fully removed. Maybe this should be considered in the requirements or `np.float` usage should be updated?

**Comment by fabian-sp** [comment]
Thanks for pointing this out. I will replace `np.float` by `np.float64,..`

Somehow in Colab, if I install a numpy version > 1.22.0 it still seems to work though (I only get the DeprecationWarning).

**Comment by Bpoole908** [comment]
There could be additional versions that only still throw the DeprecationWarning. I believe I originally observed that 1.25.2 throws a full error. I didn't test every version in-between sadly. I found 1.22.0 worked and went with that for now.

**Comment by fabian-sp** [comment]
I update the package (to version 0.1.10) and it should now also work with the newest versions of numpy.
